# intents_config.yaml
mcp_schema_version: "1.0"
intents:
  - name: "GetProducts"
    description: "Fetches a list of products from Salesforce."
    slots:
      - name: "product_family"
        type: "String"
        description: "The category or family of products (e.g., 'Solar panels'). Optional."
        required: false
    training_phrases:
      - "What are our products?"
      - "Show me all products."
      - "List products."
      - "What [product_family] do you offer?"
      - "Do you have [product_family]?"
      - "Give me a list of [product_family]."

  - name: "UnsupportedRequest"
    description: "Used when the user's query is not recognized or out of scope."
    slots: []
    training_phrases:
      - "What is the current time?"
      - "Tell me something interesting."
      - "How are you?"